apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: appeals-status-api
  description: Appeals Status APIs for VA Lighthouse program
  title: Appeals Status API
  tags:
    - lighthouse
    - external
  links:
    - url: https://developer.va.gov/explore/appeals/docs/appeals
      title: Public Docs
      icon: web
spec:
  type: openapi
  lifecycle: production
  owner: lighthouse-banana-peels
  system: vets-api
  definition:
    $text: https://github.com/department-of-veterans-affairs/vets-api/blob/master/modules/appeals_api/app/swagger/v0/appeals.yml
