version: 2
registries:
  rubygems-server-enterprise-contribsys-com:
    type: rubygems-server
    url: https://enterprise.contribsys.com/
    username: "${{secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM_USERNAME}}"
    password: "${{secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM_PASSWORD}}"
updates:
  - package-ecosystem: bundler
    directory: "/"
    insecure-external-code-execution: allow
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    cooldown:
      semver-major-days: 21
      semver-minor-days: 14
      semver-patch-days: 7
    ignore:
      - dependency-name: "vets_json_schema"
      - dependency-name: "sidekiq"
      - dependency-name: "sidekiq-pro"
      - dependency-name: "sidekiq-ent"
    open-pull-requests-limit: 5
    registries:
    - rubygems-server-enterprise-contribsys-com
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
