{{- $root := . -}}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: common-environment-ssm-vars
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-3"
spec:
  secretStoreRef:
    name: vets-api-ssm-secretstore
    kind: SecretStore
  dataFrom:
    - find:
        path: /dsva-vagov/vets-api/{{ $root.Values.target_env }}/env_vars
        name:
          regexp: .*
      rewrite:
        - regexp:
            source: "\\/dsva-vagov\\/vets-api\\/{{ $root.Values.target_env }}\\/env_vars\\/(.*)"
            target: "SETTINGS__$1"
        - regexp:
            source: "\\/"
            target: "__"
        - regexp:
            source: "[^a-zA-Z0-9 -]"
            target: "_"
