# NOTE:
# *.va.gov = through revproxy
# *.vfs.va.gov = straight to EKS (no revproxy)
{{- if .Values.web.ingress.enabled }}
{{- $root := . -}}
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}-{{ .Values.target_env }}
spec:
  entryPoints:
    - web
  routes:
    # Iterating over a Complex Structure
    {{- range $name, $service := $root.Values.web.webServices.service }}
    {{- range $key, $key := $service }}
    - kind: {{ $root.Values.web.webServices.default.kind }}
      match: Host(`{{ $key.host | default $root.Values.web.webServices.default.host }}`) && {{ $key.path }}
      priority: {{ $key.priority | default $root.Values.web.webServices.default.priority  }}
      services:
        - name: {{ $name }}
          port: {{ $key.port | default $root.Values.web.webServices.default.port }}
      middlewares:
        - name: {{ $root.Values.web.webServices.default.middleware }}
    {{- end }}
    {{- end }}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-real-ip
  namespace: {{ .Release.Namespace }}-{{ .Values.target_env }}
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        - "1.1.1.1/24"
{{- end }}
