# NOTE:
# *.va.gov = through revproxy
# *.vfs.va.gov = straight to EKS (no revproxy)
{{- if .Values.web.ingress.enabled }}
{{- $root := . -}}
---
apiVersion: {{ $root.Values.traefikApiVersion }}
kind: IngressRoute
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
    # Iterating over a Complex Structure
    {{- range $name, $service := .Values.web.webServices }}
    {{- range $service.routes }}
    - kind: {{ .kind | default $root.Values.web.ingress.default.kind }}
      match:  Host(`{{ .host | default $root.Values.web.ingress.default.host }}`) && {{ .path }}
      priority: {{ .priority | default $root.Values.web.ingress.default.priority }}
      services:
        - name: {{ $name }}
          port: {{ .port | default $root.Values.web.ingress.default.port }}
      middlewares:
        {{- if $root.Values.web.ingress.headers.enabled }}
        - name: traefik-real-ip-headers
        {{- end }}
        - name: traefik-real-ip
    {{- end }}
    {{- end }}

---
apiVersion: {{ $root.Values.traefikApiVersion }}
kind: Middleware
metadata:
  name: traefik-real-ip
  namespace: {{ .Release.Namespace }}
spec:
  plugin:
    traefik-real-ip:
      excludednets:
        - "1.1.1.1/24"

{{- if .Values.web.ingress.headers.enabled }}
---
apiVersion: {{ $root.Values.traefikApiVersion }}
kind: Middleware
metadata:
  name: traefik-real-ip-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
{{ toYaml .Values.web.ingress.headers.properties | indent 4 }}
{{- end }}
{{- end }}
