{{- if .Values.web.service.enabled }}
# Source: confluence/templates/service.yaml
# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
# Worker env: tracks pods that deployment has
---
{{- $root := . -}}
{{- range $name, $service := $root.Values.web.externalservice.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app_name: {{ $name }}
  annotations:
{{ toYaml $root.Values.web.service.annotations | indent 4 }}
spec:
  ports:
{{ toYaml $root.Values.web.service.ports | indent 4 }}
  type: {{ $root.Values.web.service.type }}
  selector:
    app: {{ $name }}
{{- end }}
{{- end }}
