{{- if .Values.web.service.enabled }}
# Source: confluence/templates/service.yaml
# Documentation: https://kubernetes.io/docs/concepts/services-networking/service/
# Worker env: tracks pods that deployment has
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}-web
  namespace: {{ .Release.Namespace }}-{{ .Values.target_env }}
  labels:
    app_name: {{ .Values.appName }}-web
  annotations:
{{ toYaml .Values.web.service.annotations | indent 4 }}
spec:
  ports:
{{ toYaml .Values.web.service.ports | indent 4 }}
  type: {{ .Values.web.service.type }}
  selector:
    app: {{ .Values.appName }}-web
{{- end }}
