common:
  - david.mazik@va.gov
  - drew.fisher@adhocteam.us
  - eshvimmer@deloitte.com
  - janet.coutinho@va.gov
  - jeffrey.greene@pingwind.com
  - jeremy.hunton@vetsez.com
  - matthew.christianson@pingwind.com
  - mbavanaka@deloitte.com
  - michael.harlow@va.gov
  - mughumman@deloitte.com
  - robert.perea-martinez@adhocteam.us
  - rockwell.rice@pingwind.com
  - slamsal@deloitte.com
  - stone_christopher@bah.com
  - zachary.goldfine@va.gov
submission_report_mailer: []
unsuccessful_report_mailer: []