---
:main_line:
  :ssn: 9
  :file_number: 9
  :suffix: 2
  :dob: 8
  :mr_status: 1
  :rem_ent: 7
  :cert_issue_date: 8
  :del_date: 8
  :date_last_certified: 8
  :veteran_name: 20
  :address1: 20
  :address2: 20
  :address3: 20
  :address4: 20
  :address5: 20
  :zip_code: 9
  :stub_nm: 7
  :rpo_code: 3
  :fac_code: 8
  :payment_amt: 7
:award_line:
  :award_begin_date: 8
  :award_end_date: 8
  :training_time: 1
  :payment_date: 8
  :monthly_rate: 7
  :begin_rsn: 2
  :end_rsn: 2
  :type_training: 1
  :number_hours: 2
  :type_hours: 1
  :cur_award_ind: 1
:mappings:
  :profile:
  - :ssn
  - :file_number
  :info:
  - :file_number
  - :dob
  - :mr_status
  - :rem_ent
  - :cert_issue_date
  - :del_date
  - :date_last_certified
  - :stub_nm
  - :rpo_code
  - :fac_code
  - :payment_amt
  - :indicator
  :address:
  - :veteran_name
  - :address1
  - :address2
  - :address3
  - :address4
  - :address5
  - :zip_code
:indicator: true
