development: &defaults
  issuer: saml-rp.vetsgov.localhost
  callback_url: http://localhost:3000/auth/saml/callback
  metadata_url: https://api.idmelabs.com/saml/metadata
  certificate: <%= File.read(File.expand_path(ENV["CERTIFICATE_FILE"])).dump %>
  key: <%= File.read(File.expand_path(ENV["KEY_FILE"])).dump %>
  relay_url: http://localhost:3001

test:
  <<: *defaults
  certificate: <%= File.read("spec/support/certificates/ruby-saml.crt").dump %>
  key: <%= File.read("spec/support/certificates/ruby-saml.key").dump %>

production:
  issuer: <%= ENV["SAML_ISSUER"] %>
  callback_url: <%=ENV["CALLBACK_URL"] %>
  metadata_url: <%= ENV["METADATA_URL"] %>
  certificate: <%= File.read(File.expand_path(ENV["CERTIFICATE_FILE"])).dump %>
  key: <%= File.read(File.expand_path(ENV["KEY_FILE"])).dump %>
  relay_url: <%=ENV["RELAY_URL"] %>
