common:
  - michael.hobson@adhocteam.us
  - kristen.brown@adhocteam.us
  - mmcdonald@technatomy.com
  - pstevens@technatomy.com
  - alattimore@technatomy.com
  - dorner_brandon@bah.com
  - eshvimmer@deloitte.com
  - slamsal@deloitte.com
  - mughumman@deloitte.com
  - mbavanaka@deloitte.com
development:
staging:
sandbox:
production:
  - cory.sohrakoff@va.gov
  - drew.fisher@adhocteam.us
  - jacob.worrell@va.gov
  - janet.coutinho@va.gov
  - john.gosnell@va.gov
  - matthew.self2@va.gov
  - premal.shah@va.gov
  - steve.albers@va.gov
  - zachary.goldfine@va.gov

