---
http_interactions:
  - request:
      method: get
      uri: https://veteran.apps.va.gov/facilities/v2/scheduling/configurations?ccEnabled=false&facilityIds=489&pageSize=0
      body:
        encoding: US-ASCII
        string: ""
      headers:
        Accept:
          - application/json
        Content-Type:
          - application/json
        User-Agent:
          - Vets.gov Agent
        Referer:
          - https://review-instance.va.gov
        X-Vamf-Jwt:
          - stubbed_token
        X-Request-Id:
          - ""
        Accept-Encoding:
          - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
    response:
      status:
        code: 200
        message: Success
      headers:
        Date:
          - Tue, 11 May 2021 19:08:53 GMT
        Content-Type:
          - application/json
        Content-Length:
          - "982"
        Connection:
          - keep-alive
        Etag:
          - '"601db677-1493"'
        Set-Cookie:
          - TS016f4012=01c8917e48d9a50f9b8e2312e887d53e871c44f1f8a90bd4484cdf6bd4bfb539515b3dad276e40d91091884ca4c48334e49b5a63ad;
            Max-Age=900; Path=/
          - vamfjwtv3=eyJ6aXAiOiJERUYiLCJjdHkiOiJKV1QiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiYWxnIjoiUlNBLU9BRVAtMjU2In0.bMSrBhLYe6SrnX5Dzv2u_UBwTmya7Eg_z2epaYFrx2Ho5_RY2SUIwV03uWt6Y8T5RTdflZwWJgn2gxhG91vqBOpktMigXPZHisUbYdC3yeACtMozGtzlzkFWPaB22aVjRlx-aQnzWdWNTIrkKBiJGxqQm6bf04CebJ_0ML8JPF0oOUHNElsSOSxiBSKpgWT6Oshi5t_cfjbabHgtYrBVEDFDSV5_r8g7Xgjcr62GBMJ_OC-5-HuDRHHeDN8yY11ttEeHlVR18pMGv9jkKanv0GMhJTygAfhCZzBp9eSkFH0zJN7FbZN49_C62BDQH5M0UoWWN63OSr2iqjbxY6B2nA.527KLAwO0S4C6cXx0iTRSA.F_Hd3w76IWTZwPiCSLkEWBl3wzwxJBiaOXYweooMMmHYScpyGDO1ixPFLL1QZICr0UoHyrsLIIVj76wqfus2n6A9b1IM4BxnyXUMUAdRc5s6DX4KQHNZTvllIya-89yqvY9xDt_ZRK-KoU3ZEwKCrNqoI4OGK1_1jp9ccfOwB2I_5OOhEniqnBXTyfdWFHfuCL4tT3W8U_LOfVr95cvotxvwaEWwv8LT_5XgNhQX2m0K4D565HLaxRr1py6swlfAn6F50Dk2whg5wGjOdUPf8PmDFNpZAdB0kX-uxmQqRMaG0lcSjGujFDcBNSGpFk1_uFYHdKbctquRH5jjXJkDJjV3Z4Pw6hQUTqMl4zepAYM-NcrxbjQqniUWQ0wuBmm81ui_GtCEKXgfZPcgsb3PgKUJoO7pQ389kevlx89vWLrjhgFvNA8Wpex04PRgm5Z890tBHzUsjTI7FHE4FYk_KZX2wcAfCP78YbqP8-JxV62rXZBuSEaNUDiSB2uGyXJjvq8D1E5S7dH8USx-LAHkXnmnbK8aCMKJMi9EhEDrSCHYQ-4mc3WhJr7QrXto5jKjffj1jepnH_Q1BsX3GB_ODKDDobTJWmOtHn8kCYHuovmOAz1c6WQy08LCJz2bS63vZFlRaehon5qt7lKxluisCapAilBUNcEATU4z9fjJFHRlOsDv83DRSzTw2eSqaG5u36tLtveu7ITZnV5XYskMrg.G1phc_CuBNPFnFw5AEYSqSLyWsMDqhg9m_Czt3_28iQ;
            path=/; SameSite=Lax; HttpOnly
          - vamftimeoutv1=1620761033; SameSite=Lax; path=/
      body:
        encoding: UTF-8
        string: |-
          {
            "data": [
              {
                "facilityId": "489",
                "services": [
                  {
                    "id": "",
                    "name": "Primary Care",
                    "stopCodes": [
                      {
                        "primary": "",
                        "secondary": ""
                      }
                    ],
                    "char4": "CDQC",
                    "direct": {
                      "patientHistoryRequired": true,
                      "patientHistoryDuration": 0,
                      "canCancel": true,
                      "enabled": true
                    },
                    "request": {
                      "patientHistoryRequired": true,
                      "patientHistoryDuration": 0,
                      "canCancel": true,
                      "submittedRequestLimit": 0,
                      "enterpriseSubmittedRequestLimit": 0,
                      "supported": true,
                      "schedulingDays": [
                        {
                          "day": "",
                          "canSchedule": true,
                          "startTime": "",
                          "endTime": ""
                        }
                      ]
                    }
                  }
                ],
                "communityCare": true
              }
            ]
          }
        http_version:
    recorded_at: Tue, 11 May 2021 19:08:53 GMT
recorded_with: VCR 6.0.0
