veteran_full_name: [identity_information, full_name]
veteranSocialSecurityNumber: [identity_information, ssn]
gender: [identity_information, gender]
veteranDateOfBirth: [identity_information, date_of_birth]
homePhone: [contact_information, us_phone]
veteranAddress: [contact_information, address]
email: [contact_information, email]
providers: [ezr_data, providers]
isMedicaidEligible: [ezr_data, isMedicaidEligible]
isEnrolledMedicarePartA: [ezr_data, isEnrolledMedicarePartA]
medicarePartAEffectiveDate: [ezr_data, medicarePartAEffectiveDate]
medicareClaimNumber: [ezr_data, medicareClaimNumber]
spouseFullName: [ezr_data, spouseFullName]
spouseSocialSecurityNumber: [ezr_data, spouseSocialSecurityNumber]
spouseDateOfBirth: [ezr_data, spouseDateOfBirth]
dateOfMarriage: [ezr_data, dateOfMarriage]
cohabitedLastYear: [ezr_data, cohabitedLastYear]
maritalStatus: [ezr_data, maritalStatus]
dependents: [ezr_data, dependents]
nextOfKins: [ezr_data, nextOfKins]
emergencyContacts: [ezr_data, emergencyContacts]
nonPrefill:
  previousFinancialInfo: [ezr_data, previousFinancialInfo]
