veteran_full_name: [identity_information, full_name]
gender: [identity_information, gender]
veteranDateOfBirth: [identity_information, date_of_birth]
veteranSocialSecurityNumber: [identity_information, ssn]
homePhone: [contact_information, home_phone]
veteranAddress: [contact_information, address]
email: [contact_information, email]
