veteran_full_name: [identity_information, full_name]
gender: [identity_information, gender]
veteranDateOfBirth: [identity_information, date_of_birth]
veteranSocialSecurityNumber: [identity_information, ssn]
homePhone: [contact_information, us_phone]
veteranAddress: [contact_information, address]
email: [contact_information, email]
lastServiceBranch: [military_information, hca_last_service_branch]
lastEntryDate: [military_information, last_entry_date]
lastDischargeDate: [military_information, last_discharge_date]
discharge_type: [military_information, discharge_type]
postNov111998Combat: [military_information, post_nov111998_combat]
swAsiaCombat: [military_information, sw_asia_combat]
