userInformation:
  fullName: [identity_information, full_name]
  dob: [identity_information, date_of_birth]
  phoneNumber: [contact_information, us_phone]
  email: [contact_information, email]
  address: [contact_information, address]

