personalInformation:
  fullName: [identity_information, full_name]
  dateOfBirth: [identity_information, date_of_birth]
  ssn: [identity_information, ssn]
contactInformation:
  email: [contact_information, email]
  address: [contact_information, address]
  primaryPhone: [contact_information, us_phone]
militaryInformation:
  serviceBranch: [military_information, last_service_branch]
  serviceDateRange:
    from: [military_information, last_entry_date]
    to: [military_information, last_discharge_date]
identityValidation:
  hasICN: [identity_validation, has_icn]
  hasParticipantId: [identity_validation, has_participant_id]
  isLoa3: [identity_validation, is_loa3]
