veteranFullName: [identity_information, full_name]
zipCode: [identity_information, full_name]
veteranSocialSecurityNumber: [identity_information, ssn]
veteranAddress: [contact_information, address]
address: [contact_information, address]
fileNumber: [contact_information, ssn]
address: [contact_information, address]
veteranPhone: [contact_information, us_phone]
email: [contact_information, email]
emailAddress: [contact_information, email]
email_address: [contact_information, email]
veteranDateOfBirth: [identity_information, date_of_birth]
