veteran_full_name: [identity_information, full_name]
veteran_date_of_birth: [identity_information, date_of_birth]
veteran_social_security_number: [identity_information, ssn]
veteran_address: [contact_information, address]
email: [contact_information, email]
phone: [contact_information, us_phone]
mobile_phone: [contact_information, mobile_phone]
international_phone: [contact_information, home_phone]
service_branch: [military_information, service_branches_for_pensions]
active_service_date_range:
  from: [military_information, first_uniformed_entry_date]
  to: [military_information, last_active_discharge_date]
service_number: [military_information, service_number]
