veteranFullName: [identity_information, full_name]
userFullName: [identity_information, full_name]
gender: [identity_information, gender]
veteranDateOfBirth: [identity_information, date_of_birth]
veteranSocialSecurityNumber: [identity_information, ssn]
homePhone: [contact_information, us_phone]
mobilePhone: [contact_information, mobile_phone]
veteranAddress: [contact_information, address]
email: [contact_information, email]
toursOfDuty: [military_information, tours_of_duty]
currentlyActiveDuty: [military_information, currently_active_duty_hash]