veteranFullName: [identity_information, full_name]
veteranSocialSecurityNumber: [identity_information, ssn]
homePhone: [contact_information, us_phone]
mobilePhone: [contact_information, mobile_phone]
veteranAddress: [contact_information, address]
email: [contact_information, email]
schoolName: [school_information, name]
schoolCity: [school_information, city]
schoolState: [school_information, state]
schoolCountry: [school_information, country]
remainingEntitlement:
  months: [remaining_entitlement, months]
  days: [remaining_entitlement, days]
