applicantFullName: [identity_information, full_name]
applicantGender: [identity_information, gender]
dateOfBirth: [identity_information, date_of_birth]
applicantSocialSecurityNumber: [identity_information, ssn]
dayTimePhone: [contact_information, us_phone]
nightTimePhone: [contact_information, mobile_phone]
mailingAddress: [contact_information, address]
emailAddress: [contact_information, email]
activeDuty: [military_information, currently_active_duty]
bankAccount:
  bankAccountType: [payment_information, account_type]
  bankAccountNumber: [payment_information, account_number]
  bankRoutingNumber: [payment_information, routing_number]
  bankName: [payment_information, bank_name]
