applicantFullName: [identity_information, full_name]
dateOfBirth: [identity_information, date_of_birth]
ssn: [identity_information, ssn]
contactInfo:
  emailAddress: [contact_information, email]
  homePhone: [contact_information, us_phone]
  mobilePhone: [contact_information, mobile_phone]
mailingAddress: [contact_information, address]
bankAccount:
  bankAccountType: [payment_information, account_type]
  bankAccountNumber: [payment_information, account_number]
  bankRoutingNumber: [payment_information, routing_number]
  bankName: [payment_information, bank_name]
