claimantAddress:
  countryName: [contact_information, address, country]
  addressLine1: [contact_information, address, street]
  addressLine2: [contact_information, address, street2]
  city: [contact_information, address, city]
  stateCode: [contact_information, address, state]
  zipCode: [contact_information, address, postal_code]
claimantPhoneNumber: [contact_information, us_phone]
claimantEmailAddress: [contact_information, email]
