fullName: [identity_information, full_name]
permanentAddress: [mdot_contact_information, permanent_address]
temporaryAddress: [mdot_contact_information, temporary_address]
ssnLastFour: [identity_information, ssn_last_four]
gender: [identity_information, gender]
email: [contact_information, email]
dateOfBirth: [identity_information, date_of_birth]
eligibility: [mdot_supplies, eligibility]
supplies: [mdot_supplies, available]
