---
http_interactions:
- request:
    method: get
    uri: "<MHV_HOST>/v1/sm/patient/preferences/notification"
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      User-Agent:
      - Vets.gov Agent
      Token: "<SESSION_TOKEN>"
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      X-Powered-By:
      - Servlet/2.5 JSP/2.1
      Content-Type:
      - application/json
      Content-Length:
      - '62'
      Date:
      - Tue, 02 May 2017 06:33:48 GMT
    body:
      encoding: UTF-8
      string: '{"emailAddress":"muazzam.khan@va.gov","notifyMe":"Once daily"}'
    http_version: 
  recorded_at: Tue, 02 May 2017 06:33:48 GMT
recorded_with: VCR 3.0.3
