---
http_interactions:
- request:
    method: get
    uri: https://essapi-sysb.myhealth.va.gov/mhv-api/patient/v1/preferences/email
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      User-Agent:
      - Vets.gov Agent
      Token:
      - 102OTc4NjU0MjE=0p9Dh7Xk3oNW1O2dKqh25m+46fpR3+VCLzU8+lJDUYU=
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: OK
    headers:
      Server:
      - Apache-Coyote/1.1
      Content-Type:
      - application/json
      Content-Length:
      - '46'
      Date:
      - Mon, 20 Mar 2017 17:55:42 GMT
    body:
      encoding: UTF-8
      string: '{"emailAddress":"Praneeth.Gaganapally@va.gov"}'
    http_version: 
  recorded_at: Mon, 20 Mar 2017 17:55:42 GMT
recorded_with: VCR 3.0.3
