name: Pact Contract Tests
on: [workflow_dispatch]
jobs:
  tests:
    name: Pact Contract Tests
    runs-on: ubuntu-20.04
    env:
      BUNDLE_ENTERPRISE__CONTRIBSYS__COM: ${{ secrets.BUNDLE_ENTERPRISE__CONTRIBSYS__COM }}
      DATABASE_URL: "postgis://vets-api:postgres@127.0.0.1:5432/vets-api-test"
      RAILS_ENV: test
      PGHOST: localhost
      PGUSER: vets-api
      PGPASSWORD: postgres
      "Settings.test_database_url": "postgis://vets-api:postgres@127.0.0.1:5432/vets-api-test"

    services:
      postgres:
        image: postgis/postgis:11-2.5
        credentials:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        env:
          POSTGRES_USER: vets-api
          POSTGRES_DB: vets-api-test
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 15

      redis:
        image: circleci/redis:5.0-alpine
        credentials:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-gov-west-1"

      - name: Get bot token from Parameter Store
        uses: marvinpinto/action-inject-ssm-secrets@v1.2.1
        with:
          ssm_parameter: /dsva-vagov/pact-broker/utility/PACT_BROKER_BASIC_AUTH_PASSWORD
          env_variable_name: PACT_BROKER_BASIC_AUTH_PASSWORD

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install dependencies (pdftk, poppler, imagemagick)
        run: sudo apt install imagemagick pdftk poppler-utils

      - name: Setup Database
        run: bundle exec rake db:schema:load

      - name: Verify stable Pacts
        run: bundle exec rake pact:verify
        env:
          PACT_BROKER_BASIC_AUTH_USERNAME: pact-broker
          PACT_BROKER_BASE_URL: https://dev.va.gov/_vfs/pact-broker/
