---
http_interactions:
- request:
    method: get
    uri: https://fake_url.com/eligibility-manager/api/eligibility/application?edipi=384759483&icn=24811694708759028
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Content-Type:
      - application/json
      User-Agent:
      - Vets.gov Agent
      Authorization:
      - 'api-key { "appId":"fake_app_id", "apiKey": "fake_api_key"}'
      Accept-Encoding:
      - gzip;q=1.0,deflate;q=0.6,identity;q=0.3
  response:
    status:
      code: 200
      message: ''
    headers:
      Server:
      - nginx/1.21.0
      Date:
      - Thu, 20 Jan 2022 23:45:00 GMT
      Content-Type:
      - application/json
      Transfer-Encoding:
      - chunked
      Connection:
      - keep-alive
      X-Oneagent-Js-Injection:
      - 'true'
      X-Lgyrequestuuid:
      - 7f50cb22184578b9
      X-Content-Type-Options:
      - nosniff
      X-Xss-Protection:
      - 1; mode=block
      Cache-Control:
      - no-cache, no-store, max-age=0, must-revalidate
      Pragma:
      - no-cache
      Expires:
      - '0'
      Strict-Transport-Security:
      - max-age=31536000 ; includeSubDomains
      X-Frame-Options:
      - SAMEORIGIN
      Via:
      - 1.0 sqa.services.lgy.va.gov
      Server-Timing:
      - dtSInfo;desc="0", dtRpid;desc="640242957"
    body:
      encoding: UTF-8
      string: '{"id":4771462,"createDate":1642619386000,"status":"SUBMITTED","veteran":{"firstName":"PAULINE","middleName":"E","lastName":"FOSTER","suffixName":"III","vetAddress1":"123
        MAIN ST","vetAddress2":null,"vetCity":"MANTUA","vetState":"NJ","vetZip":"08051","vetZipSuffix":null,"mailingAddress1":"123
        MAIN ST","mailingAddress2":null,"mailingCity":"MANTUA","mailingState":"NJ","mailingZip":"08051","mailingZipSuffix":null,"contactPhone":"8007271000","contactEmail":"vets.gov.user38@gmail.com","vaLoanIndicator":false,"vaHomeOwnIndicator":false,"activeDutyIndicator":false,"disabilityIndicator":false},"relevantPriorLoans":[],"periodsOfService":[{"enteredOnDuty":1546322400000,"releasedActiveDuty":1577685600000,"serviceType":"ACTIVE_DUTY","characterOfService":null,"militaryBranch":null,"activeDutyPoints":null,"inactiveDutyPoints":null,"qualifies":null,"rankCode":"ENLISTED","disabilityIndicator":false},{"enteredOnDuty":1514786400000,"releasedActiveDuty":1522386000000,"serviceType":"RESERVE_NATIONAL_GUARD","characterOfService":null,"militaryBranch":null,"activeDutyPoints":null,"inactiveDutyPoints":null,"qualifies":null,"rankCode":"ENLISTED","disabilityIndicator":false}]}'
  recorded_at: Thu, 20 Jan 2022 23:45:00 GMT
recorded_with: VCR 6.0.0
